### ISSUE TITLE
Table CRC Tool Fails to Close File Descriptor

### ISSUE THREAD

**Issue by skliper** [nasa/tblCRCTool#1]
Analysis of the 27b VPU FSW code revealed that there is a potential leak of an allocated resource in the file cfe_ts_crc.c. The resource "fd" is opened but never closed before the function returns.

VpuTopProject/cfs/CFE/tools/tblCRCTool/cfe_ts_crc.c
143 /* open the input file if possible */
-->144 fd = open( argv[1], O_RDONLY );
145 if ( fd < 0 )
146 {
147 printf("\ncfe_ts_crc error: can't open input file!\n");
148 exit(0);
149 }
150 /* seek past the number of bytes requested */
151 lseek( fd, skipSize, SEEK_SET );
152 
153 /* read the input file 100 bytes at a time */
154 while ( done == 0 )
155 {
156 readSize = read(fd, buffer, 100);
157 fileCRC = CFE_ES_CalculateCRC(buffer, readSize, fileCRC, CFE_ES_CRC_16);
158 fileSize += readSize;
159 if (readSize != 100) done=1; 
160 }
161 /* print the size/CRC results */
162 printf("\nTable File Name: %s\nTable Size: %d Bytes\nExpected TS Validation CRC: 0x%08X\n\n", argv[1], fileSize, fileCRC);
163
164 return(fileCRC);
165 }

**Comment by avan989** [comment]
I can do this.
