### ISSUE TITLE
tblCRCTool needs a CMakeLists.txt file implemented

### ISSUE THREAD

**Issue by jphickey** [nasa/tblCRCTool#10]
**Describe the bug**
This tool is not built like the rest of them, still using a one-off Makefile.

**To Reproduce**
Build CFE using the recommended CMake practice.  This tool is not built.  The user must then manually build the tool within the source directory.

**Expected behavior**
The tool should be built as part of the overall mission build and installed to the "host" directory.

**System observed on:**
Ubuntu 18.04 (64-bit)

**Reporter Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by skliper** [comment]
Need to confirm original makefile gets removed so there is no chance of getting a cfe_ts_crc in this directory.

**Comment by skliper** [comment]
> Need to confirm original makefile gets removed so there is no chance of getting a cfe_ts_crc in this directory.

Confirmed.
