### ISSUE TITLE
tblCRCTool hardcodes table file header size

### ISSUE THREAD

**Issue by skliper** [nasa/tblCRCTool#3]
Maintenance issue with hardcoded header size in tblCRCTool

**Comment by avan989** [comment]
Can you give an example of what you are referring to?

**Comment by skliper** [comment]
The issue is about skipSize hardcoded to 116.  Not clear where that number comes from, but likely related to CFE_FS_Header_t and/or CFE_TBL_File_Hdr_t (as seen in the CFE_TBL_LoadCmd from cfe/fsw/cfe-core/src/tbl/cfe_tbl_task_cmds.c)  Take a look at that code and see if you can figure it out.

**Comment by skliper** [comment]
https://github.com/nasa/cFE/pull/25 has been merged, this can now be implemented.
