### ISSUE TITLE
Incorrect EOF check

### ISSUE THREAD

**Issue by jphickey** [nasa/tblCRCTool#41]
**Describe the bug**
The end-of-file test in this tool is incorrect:

https://github.com/nasa/tblCRCTool/blob/b02864ba56b12e00ab152225e3e8f9d6c039d48c/cfe_ts_crc.c#L139

POSIX says that `read()` returns 0 at EOF.  Returning a size less than the requested size (but more than 0) does not mean EOF.

**To Reproduce**
A mainly pedantic issue, this check as it is will probably work on regular files, but it might fail of someone tries to make this work on a pipe or something like that.

**Expected behavior**
Should check if `read()` returned 0, not 100.

**System observed on:**
Code review

**Additional Context**
While we are at it we should change the hardcoded `100` to be `sizeof(buffer)` too.

**Reporter Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by zanzaben** [comment]
read returns the number of bytes it read so since we are reading it in batches we need to know when we are on the last batch which could be any number less than 100 not necessarily 0.

**Comment by jphickey** [comment]
> read returns the number of bytes it read so since we are reading it in batches we need to know when we are on the last batch which could be any number less than 100 not necessarily 0.

This is true - but this does _not_ mean EOF.   To be correct it should repeat the loop, call `read()` again, and it will get 0 at that time if it is actually EOF.

The detail here is that it should not just assume a short read indicates EOF.  It _probably_ does mean EOF - particularly on a regular file.  But on a pipe or socket or other non-regular file details like this do make a difference.  Implementation is allowed to return fewer bytes than requested for a number of reasons, not just EOF.
