### ISSUE TITLE
Gitignore cfe_ts_crc

### ISSUE THREAD

**Issue by skliper** [nasa/tblCRCTool#9]
**Is your feature request related to a problem? Please describe.**
Executable shows up as untracked file

**Describe the solution you'd like**
Add cfe_ts_crc to .gitignore

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman/NASA GSFC

**Comment by jphickey** [comment]
Note This isn't necessary if we merge #10 instead, which I already have implemented.

**Comment by skliper** [comment]
Great point assuming your change removes the original make file.  I'll remove/cancel.

**Comment by skliper** [comment]
No longer needed with #10, closing.
